[general]
bars = 24
framerate = 60

[input]
method = pulse
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
bit_format = 8bit

[smoothing]
noise_reduction = 66
