background            #0B0B0B
foreground             #F3F3F3
cursor                 #F3F3F3
selection_background   #F15A52
selection_foreground   #0B0B0B

color0                 #0B0B0B
color8                 #303030

color1                 #EB514B
color9                 #F15A52

color2                 #E6E6E6
color10                #F3F3F3

color3                 #FF7770
color11                #FF7770

color4                 #969696
color12                #E6E6E6

color5                 #F15A52
color13                #FF7770

color6                 #E6E6E6
color14                #F3F3F3

color7                 #F3F3F3
color15                #F3F3F3
