$wallpaper = /home/kuro/Pictures/Wallpapers/024.jpg
$lock_outer = 42, 42, 66
$lock_inner = 10, 10, 18
$lock_font = 232, 245, 242
$lock_check = 62, 232, 200
$lock_fail = 181, 105, 224
$lock_accent = 62, 232, 200
