$wallpaper = /home/kuro/Pictures/Wallpapers/025.jpg
$lock_outer = 34, 56, 106
$lock_inner = 12, 26, 58
$lock_font = 232, 238, 248
$lock_check = 74, 143, 212
$lock_fail = 212, 176, 106
$lock_accent = 74, 143, 212
