$wallpaper = /home/sofyan/Pictures/Wallpapers/003.jpg
$lock_outer = 58, 63, 77
$lock_inner = 32, 35, 44
$lock_font = 178, 184, 194
$lock_check = 229, 192, 120
$lock_fail = 175, 75, 87
$lock_accent = 229, 192, 120
