$wallpaper = $HOME/Pictures/Wallpapers/002.jpeg

background {
    monitor =
    path = $wallpaper
    blur_passes = 2
    blur_size = 7
    noise = 0.0117
    contrast = 1.0
    brightness = 0.75
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

general {
    hide_cursor = true
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgb(74, 42, 40)
    inner_color = rgb(20, 12, 13)
    font_color = rgb(245, 230, 220)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    check_color = rgb(217, 162, 95)
    fail_color = rgb(180, 85, 68)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    position = 0, -120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(255, 255, 255, 1.0)
    font_size = 120
    font_family = Maple Mono NF
    shadow_passes = 3
    shadow_size = 5
    shadow_color = rgba(0, 0, 0, 0.9)
    shadow_boost = 1.6
    position = 0, 300
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B %Y")"
    color = rgba(240, 225, 220, 1.0)
    font_size = 22
    font_family = Maple Mono NF
    shadow_passes = 3
    shadow_size = 4
    shadow_color = rgba(0, 0, 0, 0.9)
    shadow_boost = 1.6
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(245, 195, 130, 1.0)
    font_size = 20
    font_family = Maple Mono NF
    shadow_passes = 3
    shadow_size = 4
    shadow_color = rgba(0, 0, 0, 0.9)
    shadow_boost = 1.6
    position = 0, -40
    halign = center
    valign = center
}
